baseURL                = "https://ishareread.github.io/"
languageCode           = "zh-CN"
title                  = "爱分享读书"
defaultContentLanguage = "zh"
hasCJKLanguage         = true
paginate               = 10

theme = "hugo-theme-stack"

[permalinks]
    post = "/p/:slug/"
    page = "/:slug/"

[pagination]
    pagerSize = 10

[sitemap]
    changefreq = "weekly"
    filename   = "sitemap.xml"
    priority   = 0.5
