[zh]
    languageName = "简体中文"
    title        = "📖 爱分享读书"
    weight       = 1

    [zh.params.sidebar]
        subtitle = "用阅读拓展认知边界"

    [zh.menu]
        [[zh.menu.main]]
            identifier = "home"
            name       = "首页"
            url        = "/"
            weight     = 1
            [zh.menu.main.params]
                icon = "home"
                newTab = false

        [[zh.menu.main]]
            identifier = "archives"
            name       = "归档"
            url        = "/archives/"
            weight     = 2
            [zh.menu.main.params]
                icon = "archives"
                newTab = false

        [[zh.menu.main]]
            identifier = "categories"
            name       = "分类"
            url        = "/categories/"
            weight     = 3
            [zh.menu.main.params]
                icon = "categories"
                newTab = false

        [[zh.menu.main]]
            identifier = "tags"
            name       = "标签"
            url        = "/tags/"
            weight     = 4
            [zh.menu.main.params]
                icon = "tag"
                newTab = false

        [[zh.menu.main]]
            identifier = "about"
            name       = "关于"
            url        = "/about/"
            weight     = 5
            [zh.menu.main.params]
                icon = "user"
                newTab = false
