[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/xiejava1018"

    [social.params]
        icon = "brand-github"

[[social]]
    identifier = "wechat"
    name       = "微信公众号"
    url        = "/subscribe/"

    [social.params]
        icon = "brand-wechat"

[[social]]
    identifier = "rss"
    name       = "RSS"
    url        = "/index.xml"

    [social.params]
        icon = "rss"
